INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (1, 1, 'Dos banderolas de color rojo de tamaño no menor a 50 centímetros por lado o reflejantes del mismo color', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (2, 1, 'Linternas en manos', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (3, 1, 'Linternas, luces de color rojo', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (4, 1, 'A y C son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (5, 2, 'Verde rosa y amarillo', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (6, 2, 'Rojo, azul y amarillo', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (7, 2, 'Rojo, verde y morado', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (8, 2, 'Azul, blanco y verde', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (9, 3, '10km/h', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (10, 3, '30km/h', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (11, 3, '15km/h', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (12, 3, '40km/h', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (13, 4, 'Vías restringidas ', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (14, 4, 'Vías limitadas', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (15, 4, 'A y B son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (16, 4, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (17, 5, 'Cada ocupante', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (18, 5, 'Del conductor del vehículo', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (19, 5, 'Del propietario del vehículo', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (20, 5, 'No se está obligado a utilizarlo', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (21, 6, 'Restrictivas', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (22, 6, 'Preventivas', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (23, 6, 'Informativas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (24, 6, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (25, 7, 'Un vehículo de 4 ruedas', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (26, 7, 'Vehículo con 2 ruedas y pedales', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (27, 7, 'Un vehículo con pedales y ruedas y que circula por la carretera', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (28, 7, 'Vehículo con motor que puede ser guiado para marchar por vía ordinaria', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (29, 8, 'Torretas de color rojo', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (30, 8, 'Torretas de color verde', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (31, 8, 'De color azul', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (32, 8, 'Torretas de color ámbar', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (33, 9, 'Tienes 0.80 y menos de 1.5 gramos de alcohol por litro de sangre', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (34, 9, 'Menos de 0.80 gramos de alcohol por litro de sangre', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (35, 9, 'Tienes 1.5 o más gramos de alcohol por litro de sangre', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (36, 9, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (37, 10, 'Efectuar piruetas o zigzaguear', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (38, 10, 'Utilizar auriculares o sistemas de comunicación de operación manual', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (39, 10, 'Usar casco protector el conductor y en su caso su acompañante, así como portar lentes u otros protectores oculares', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (40, 10, 'Todas las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (41, 11, 'Por orden judicial', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (42, 11, 'Al conducir bajo influjo de drogas o sustancias tóxicas, en 3 ocasiones en un periodo de 6 meses', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (43, 11, 'Por abandonar injustificadamente el lugar de un hecho de tránsito en más de una ocasión en un periodo de 2 años', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (44, 11, 'Todas las anteriores', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (45, 12, 'Vía publica', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (46, 12, 'Vías limitadas', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (47, 12, 'Vías restringidas', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (48, 12, 'A y B son correctas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (49, 13, '4 metros por cada 10 kilómetros por hora de velocidad', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (50, 13, '3 metros por cada 10 kilómetros por hora de velocidad', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (51, 13, '6 metros por cada 10 kilómetros por hora de velocidad', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (52, 13, '10 metros por cada 10 kilómetros por hora de velocidad', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (53, 14, 'Luz roja fija y sola', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (54, 14, 'Luz roja intermitente', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (55, 14, 'Flecha roja', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (56, 14, 'Flecha verde', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (57, 15, 'Alto', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (58, 15, 'Preventiva', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (59, 15, 'Siga', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (60, 15, 'Rebasar', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (61, 16, 'Señalar la maniobra con anticipación mediante el uso de las luces direccionales o con la mano', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (62, 16, 'A y C son correctas', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (63, 16, 'Esperar a que este vacío el carril hacia donde se pretenda cambiar', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (64, 16, 'No aumentar la velocidad', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (65, 17, 'Hagan uso de sus luces rojas y blancas', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (66, 17, 'Cuando hagan uso simultáneo de su sirena y torretas de luz roja, azul, blanca o ámbar', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (67, 17, 'Hagan uso de su torreta', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (68, 17, 'A, B y C son correctas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (69, 18, 'En la parte delantera del vehículo siempre y cuando cuenten con cinturón de seguridad', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (70, 18, 'En un sistema de retención infantil o asiento elevador debidamente colocado', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (71, 18, 'A y B son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (72, 18, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (73, 19, 'Saber leer y escribir', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (74, 19, 'Tener vehículo propio', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (75, 19, 'Tomar un curso de manejo', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (76, 19, 'No ser mayor de 60 años', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (77, 20, 'Hexagonal', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (78, 20, 'Octagonal', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (79, 20, 'Circular', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (80, 20, 'Heptagonal', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (81, 21, 'Se estaciona un vehículo en zona peatonal', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (82, 21, 'Acumulan más de 2 multas', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (83, 21, 'Se hace uso de el claxon en zona de hospital', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (84, 21, 'Maneja en estado de ebriedad', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (85, 22, 'Traer una llanta de refacción', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (86, 22, 'Un juego de frenos delanteros como repuesto', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (87, 22, 'Una herramienta en buen estado para realizar cambio de llanta', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (88, 22, 'A y C son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (89, 23, 'Los automóviles', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (90, 23, 'Las avenidas sobre las calles', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (91, 23, 'La calle pavimentada sobre la no-pavimentada', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (92, 23, 'A y C son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (93, 24, 'Choque de crucero', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (94, 24, 'Hecho de transito', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (95, 24, 'Alcance', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (96, 24, 'Choque lateral', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (97, 25, '21 años', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (98, 25, '18 años', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (99, 25, '16 años', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (100, 25, '14 años', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (101, 26, 'Exceder límite de velocidad en zona urbana', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (102, 26, 'Exceder límite de velocidad en zona escolar', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (103, 26, 'A y B son correctas', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (104, 26, 'Exceder límite de velocidad en zona de hospital', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (105, 27, 'Luces estroboscópicas, sirenas, vidrios polarizados', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (106, 27, 'Mofles directos, estéreos con pantalla y luces de neón', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (107, 27, 'Radio de frecuencia policiaca, torretas sirenas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (108, 27, 'A y C son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (109, 28, 'El conductor no las ingiera', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (110, 28, 'Sean de bajo contenido de alcohol', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (111, 28, ' A y B son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (112, 28, 'A y B son incorrectas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (113, 29, 'A la derecha en calles de un solo sentido', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (114, 29, 'En la izquierda en calles de un solo sentido', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (115, 29, 'A y B son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (116, 29, 'A y B son incorrectas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (117, 30, 'Delantera', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (118, 30, 'Trasera', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (119, 30, 'Laterales', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (120, 30, 'No está prohibido', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (121, 31, 'Vehículo para transporte escolar', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (122, 31, 'Vehículos vocacionales', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (123, 31, 'Vehículos especiales', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (124, 31, 'Todas las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (125, 32, 'Circular por las ciclovías', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (126, 32, 'Respetar el derecho de tránsito y darán preferencia a los ciclistas que transiten en ellas', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (127, 32, 'A y B son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (128, 32, 'Circular muy cerca de las ciclovías con una velocidad de 30k/h', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (129, 33, '30 km/h', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (130, 33, '40km/h', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (131, 33, '50km/h', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (132, 33, '60km/h', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (133, 34, 'La compañía de seguros correspondiente', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (134, 34, 'La autoridad de tránsito municipal', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (135, 34, 'A protección civil', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (136, 34, 'A seguridad publica', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (137, 35, 'Permitido rebasar', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (138, 35, 'Prohibido rebasar', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (139, 35, 'Ambas son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (140, 35, 'Ambas son incorrectas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (141, 36, 'De 7:00 a 9:30 de 11:30 a 14:30 y de 16:30 a 18:30 hrs', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (142, 36, ' De 7:30 a 9:00 de 11:00 a 14:00 y de 16:00 a 18:00 hrs.', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (143, 36, 'De 7:45 a 9:30 de 11:15 a 14:15 y de 16:15 a 17:45 hrs.', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (144, 36, 'Ninguna de las respuestas anteriores es la correcta', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (145, 37, ' Vehículo diplomáticos o consulares', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (146, 37, 'Unidades de emergencia', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (147, 37, 'Vehículos militares', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (148, 37, ' A y B son incorrectas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (149, 38, 'Conducir en esta de ebriedad completo o estado de ebriedad incompleto', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (150, 38, 'Sujetar, con una o ambas manos aparatos de telecomunicación, teléfonos celulares radios o cualquier aparato electrónico', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (151, 38, 'Ceder el paso a los peatones cuando se tenga que atravesar la banqueta, al entrar o salir de cocheras o estacionamientos', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (152, 38, 'A y B son incorrectas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (153, 39, 'Chofer', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (154, 39, 'Automovilista', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (155, 39, 'A y B son correctas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (156, 39, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (157, 40, 'Cruce', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (158, 40, 'Acotamiento', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (159, 40, 'Isleta', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (160, 40, 'A y B son correctas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (161, 41, 'Franja dentro de la superficie de rodamiento destinada exclusivamente para la circulación ciclista', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (162, 41, 'Vía o sección de una vía exclusiva para la circulación ciclista, separada del tránsito automotor', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (163, 41, 'Es aquel que da preferencia para las bicicletas y en el que se comparte con el tránsito automotor', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (164, 41, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (165, 42, 'En calles o avenidas de doble circulación que tengan solo un carril para cada sentido, la maniobra deberá realizarse por el lado izquierdo', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (166, 42, 'Anunciar su maniobra de rebase con luces direccionales y en caso necesario con  claxon', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (167, 42, 'Ir por el lado derecho en calles o avenidas de doble circulación que tengan solamente un carril para cada sentido de circulación', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (168, 42, 'A y B son incorrectas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (169, 43, 'Alto', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (170, 43, 'Siga', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (171, 43, 'Precaución', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (172, 43, 'A y B son correctas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (173, 44, 'Informativas', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (174, 44, 'Preventivas', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (175, 44, 'Restrictivas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (176, 44, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (177, 45, 'Prohíben rebasar', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (178, 45, 'Permiten rebasar', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (179, 45, 'Indican el sentido de la circulación', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (180, 45, 'Ninguna de las respuestas anteriores es correcta', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (181, 46, 'Licencia, tarjeta de circulación y seguro', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (182, 46, 'Licencia, factura del vehículo y refrendo', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (183, 46, 'Seguro, recibo de pago de refrendo y licencia', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (184, 46, 'Factura, placas y licencias', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (185, 47, 'Siga', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (186, 47, 'Alto', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (187, 47, 'Precaución', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (188, 47, 'Nada', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (189, 48, 'Líneas de estacionamiento', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (190, 48, 'Flechas o símbolos en el pavimento', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (191, 48, 'Rayas de alto', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (192, 48, 'Combinación de rayas centrales longitudinales continuas y descontinuas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (193, 49, 'Con rayas de alto', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (194, 49, 'Rayas oblicuas', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (195, 49, 'Combinación de rayas centrales', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (196, 49, 'Rayas longitudinales continuas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (197, 50, 'Preventiva', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (198, 50, 'Restrictiva', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (199, 50, 'Informativa', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (200, 50, 'Visual', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (201, 51, 'D y C son correctas', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (202, 51, 'Acomodar la carga dentro de los límites laterales del vehículo y de forma que no obstruya su visibilidad', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (203, 51, 'Obstruir uno o más carriles de circulación por caída parcial o total de la carga', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (204, 51, 'Utilizar personas para sujetar o proteger la carga', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (205, 52, 'Alto', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (206, 52, 'Preventiva', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (207, 52, 'Siga', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (208, 52, 'Alto o reducción de velocidad', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (209, 53, 'Rayas longitudinales continuas', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (210, 53, 'Con Rayas longitudinales discontinuas', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (211, 53, 'Rayas de alto', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (212, 53, 'Con Rayas oblicuas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (213, 54, 'En avenidas con baja velocidad', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (214, 54, 'Para entrar y salir de cajones de estacionamiento', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (215, 54, 'En calles cerradas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (216, 54, 'En calles cerradas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (217, 55, 'Placas de circulación vigente', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (218, 55, 'Calcomanía de placas y refrendo vigente', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (219, 55, 'A y B son correctas', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (220, 55, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (221, 56, 'Dispositivos u objetos que se asemejen a placas de circulación nacionales o extranjeras', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (222, 56, 'Placas vigentes', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (223, 56, 'Permiso provisional vigente', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (224, 56, 'Calcomanía de placas y refrendo vigente', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (225, 57, 'Banquetas, isletas, camellones', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (226, 57, 'Áreas diseñadas para separación de carriles, rotondas, zonas peatonales', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (227, 57, 'A y B son correctas', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (228, 57, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (229, 58, 'Chofer', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (230, 58, 'Automovilista', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (231, 58, 'Auto-transportista', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (232, 58, 'Ciclista', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (233, 59, '30 días', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (234, 59, '10 días', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (235, 59, '15 días', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (236, 59, '40 días', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (237, 60, 'Circular a exceso de velocidad en zona escolar', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (238, 60, 'Multa de un parquímetro', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (239, 60, 'Proporcionar datos falsos al oficial de transito', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (240, 60, 'A y C son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (241, 61, 'Restrictivas', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (242, 61, 'Preventivas', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (243, 61, 'Informativas', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (244, 61, 'A y C son correctas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (245, 62, 'Alto', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (246, 62, 'Siga', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (247, 62, 'Preventiva', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (248, 62, 'Alto o reducción de velocidad', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (249, 63, '18 meses', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (250, 63, '1 mes', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (251, 63, '4 meses', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (252, 63, '7 meses', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (253, 64, '3 meses', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (254, 64, '18 días', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (255, 64, '24 horas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (256, 64, 'A y C son correctas', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (257, 65, 'Cuando un vehículo este indebidamente estacionado', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (258, 65, 'O cuando cause interrupción a la circulación', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (259, 65, 'Cuando esté debidamente estacionado', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (260, 65, 'A y B son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (261, 66, 'Descender siempre del lado de la banqueta o acotamiento', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (262, 66, 'Viajar sentados en el lugar que le corresponda', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (263, 66, 'Ingerir bebidas alcohólicas en vehículos', 't', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (264, 66, 'Rebasar', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (265, 67, 'Por el carril de acotamiento', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (266, 67, 'Por el carril de la izquierda', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (267, 67, 'En donde existe linea amarilla continua', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (268, 67, 'A y C son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (269, 68, 'En avenidas de alta circulación', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (270, 68, 'A media cuadra', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (271, 68, 'Ninguna de las anteriores', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (272, 68, 'A y B son correctas', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (273, 69, '30 km/h', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (274, 69, '25 km/h', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (275, 69, '60 km/h', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (276, 69, '15 km/h', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (277, 70, 'Hacer alto', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (278, 70, 'Seguir con precaución', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (279, 70, 'Detener la marcha y ceder el paso', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (280, 70, 'Ninguna de las anteriores', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (281, 71, 'Zona escolar', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (282, 71, 'Límite de velocidad', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (283, 71, 'Ceda el paso', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (284, 71, 'Cruce de ferrocarril', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (285, 72, 'Señal informativa de servicios o turistas', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (286, 72, 'Zona escolar', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (287, 72, 'Poste de kilometraje', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (288, 72, 'Pendiente peligrosa', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (289, 73, 'Incorporación de tránsito', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (290, 73, 'Cruce de ferrocarril', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (291, 73, 'Superficie derrapante', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (292, 73, 'Ceda el paso', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (293, 74, 'Incorporación de tránsito', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (294, 74, 'Cruce de ferrocarril', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (295, 74, 'Zona escolar', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (296, 74, 'Límite de velocidad', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (297, 75, 'Poste de kilometraje', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (298, 75, 'Incorporación de tránsito', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (299, 75, 'Señal informativa de servicios o turistas', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (300, 75, 'Ceda el paso', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (301, 76, 'Pendiente peligrosa', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (302, 76, 'Superficie derrapante', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (303, 76, 'Curva', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (304, 76, 'Curva sinuosa', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (305, 77, 'Zona escolar', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (306, 77, 'Curva cerrada', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (307, 77, 'Pendiente peligrosa', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (308, 77, 'Incorporación de tránsito', 't', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (309, 78, 'Zona de derrumbes', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (310, 78, 'Señal informativa de servicios o turistas', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (311, 78, 'Cruce de ganado', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (312, 78, 'Curva sinuosa', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (313, 79, 'Curva sinuosa', 't', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (314, 79, 'Curva', 'f', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (315, 79, 'Incorporación de tránsito', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (316, 79, 'Límite de velocidad', 'f', 'D');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (317, 80, 'Curva', 'f', 'A');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (318, 80, 'Curva cerrada', 't', 'B');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (319, 80, 'Curva sinuosa', 'f', 'C');
INSERT INTO opciones_respuesta (ID_OPCION, ID_PREGUNTA, DESCRIPCION_RESPUESTA, CORRECTA, INCISO) VALUES (320, 80, 'Ceda el paso', 'f', 'D');
