INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (1, 'Cuando por circunstancias ajenas al conductor, el vehículo se encuentre sobre un carril de circulación y le sea imposible el movimiento del vehículo, se deben colocar inmediatamente algunos dispositivos. ¿Cuáles son?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (2, 'Las luces distintivas de las unidades de emergencia ¿De qué color pueden ser?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (3, '¿Cuál es la velocidad máxima en estacionamientos y establecimientos qué permitan el  acceso a vehículos?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (4, '¿Cuáles son las vías de red troncal para la circulación de vehículos de transporte de carga pesada qué tengan restricción de horario?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (5, '¿De quién es obligación el qué se utilicen los cinturones de seguridad abordo de un vehículo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (6, '¿Cuáles son las señales de color amarillo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (7, '¿Qué es un automóvil?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (8, '¿Qué tipo de torretas pueden utilizar los vehículos dedicados a la conservación y mantenimiento de la vía pública?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (9, '¿Cómo se define el estado de ebriedad completo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (10, 'Los motociclistas deberán cumplir con ciertos requisitos ¿Cuáles son?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (11, '¿Cuáles son los motivos por los qué se procederá a cancelar la licencia de conducir?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (12, '¿Cuáles vías son las qué no forman parte de la red troncal y qué para la circulación de vehículos de transporte de carga pesada, se requiere de un permiso expedido por la autoridad competente?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (13, '¿Qué distancia deben conservar los conductores entre su vehículo con peso bruto menor de 3,500 (tres mil quinientos) kilogramos y el qué le antecede?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (14, '¿Qué luz es la que indica a los conductores qué deben detener sus vehículos y podrán continuar la marcha después de ceder el paso a los peatones y vehículos qué se aproximen por la calle transversal?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (15, '¿Qué indicación es cuando los policías de tránsito, promotores voluntarios de seguridad vial se encuentren dando frente o la espalda hacia la circulación?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (16, '¿De qué manera deben efectuarse los cambios de carril?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (17, '¿En que situación los conductores deberán cederle el paso y auxiliarles en el libre movimiento a los vehículos de emergencia?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (18, '¿En dónde deben de ser transportados los menores de 7 (siete) años?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (19, '¿Qué requisito es indispensable para tramitar la licencia de conducir?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (20, '¿Qué forma geométrica tiene una señal de alto?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (21, '¿Qué acción lleva la suspensión de la licencia?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (22, '¿Qué herramientas deberán de tener los vehículos de cuatro o más ruedas?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (23, '¿Quién tendrá prioridad de paso en cruceros o intersecciones donde no existan señales graficas de alto o ceda el paso, no haya semáforos funcionando normalmente y no se encuentre un policía de tránsito dirigiendo la circulación?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (24, '¿Cuál es la consecuencia de la omisión o transgresión a una norma de circulación por un conductor derivado del movimiento de uno o más vehículos, los cuales pueden chocar entre sí o con personas, semovientes u objetos ocasionándose separada o conjuntamente lesiones?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (25, '¿Cuál es la edad mínima para obtener la licencia?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (26, '¿Qué infracción o infracciones no tienen descuento según el reglamento de tránsito?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (27, '¿Qué accesorios están prohibidos en un vehículo particular?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (28, '¿Está permitido traer bebidas alcohólicas a bordo de un vehículo circulando?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (29, '¿Dónde está prohibido estacionarse?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (30, '¿En qué parte del vehículo está prohibido traer luces rojas?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (31, '¿Cuáles vehículos de apoyo o de auxilio vial están facultado para usar torretas de luces ámbar?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (32, 'En las vías de circulación en las que el municipio establezca o adopte carriles como ciclovías, ciclocarriles y carriles compartidos con ciclistas, los conductores de vehículos automotores ¿Qué deben respetar?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (33, '¿Cuál es la velocidad máxima permitida en zonas de recreo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (34, '¿Según el reglamento de tránsito a quien se debe notificar en caso de un accidente vial?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (35, '¿Qué significa la línea segmentada al centro de la calle o carretera?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (36, '¿Cuál es el horario de zonas escolares según el reglamento de tránsito?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (37, '¿Qué vehículos usan sirena y torretas de luces rojas, blancas, azules y ámbar?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (38, '¿Cuáles son las prohibiciones de los conductores de vehículos?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (39, '¿Qué tipo de conductor de vehículo de servicio particular es de diez o más pasajeros?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (40, '¿Cuál es el área definida entre carriles de tránsito para controlar el movimiento de vehículos de vehículos o para el refugio de peatones?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (41, '¿Qué es una ciclovía?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (42, 'El conductor qué va a rebasar ¿Qué debe hacer?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (43, '¿Qué nos indican los semáforos de 3 o más luces con combinación de colores verde, ámbar  y rojo la luz ámbar nos indica?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (44, '¿Qué significado tienen las señales de color amarillo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (45, '¿Qué significan las líneas continuas en medio de la calle o la carretera?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (46, '¿Qué documentos se deben portar cuando se circula dentro del municipio?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (47, '¿Qué significado tiene el frente o la espalda de un oficial de transito al dirigir el tráfico?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (48, '¿Qué señales se utilizan para orientar el movimiento o dirección qué deben seguir los vehículos que circulen sobre el carril?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (49, '¿Qué señales advierte la proximidad de un obstáculo y la existencia de áreas donde se prohíbe la circulación de vehículos?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (50, '¿Qué tipo de señal es el «alto»?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (51, '¿Qué tienen prohibido los conductores de vehículos en movimiento qué transporten carga?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (52, '¿Cuál es la señal en donde los policías de tránsito, promotores voluntarios de seguridad vial se encuentren dando cualquier perfil hacia la circulación y levanten sus brazos apuntando con la palma de la mano hacia la misma?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (53, '¿Qué señalamiento indica el límite de la superficie de rodamiento, estando prohibido circular fuera de este? ¿Cuándo se utilizan estas como división de carriles de circulación contraria, indican una prohibición de rebasar?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (54, '¿En dónde se permite circular en reversa?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (55, '¿Qué deben portar los vehículos automotores qué circulen dentro del municipio?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (56, '¿Qué queda prohibido colocar a los vehículos?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (57, '¿En qué espacio está prohibido estacionar un vehículo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (58, '¿Qué persona física o moral debidamente autorizada por la autoridad competente, para prestar servicio público o privado de autotransporte de carga?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (59, '¿Cuántos días naturales tiene de plazo el infractor para realizar el pago de su multa?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (60, '¿Qué infracciones se consideran infracciones graves?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (61, '¿Cuáles señales graficas  verticales qué tienen por objeto guiar a los usuarios sobre las calles o caminos, nombres o poblaciones, lugares de interés, servicios generales y sus distancias?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (62, '¿Cuál señal de tránsito es en donde el oficial se encuentro dando cualquier perfil hacia la circulación?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (63, 'En caso de reincidir en alguna falta o violación al reglamento de tránsito ¿Cuánto tiempo se suspenderá la licencia?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (64, 'Cuando se conduce en estado de ebriedad se suspende la licencia por un tiempo determinado. ¿Por cuánto tiempo?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (65, '¿Cuál motivo es por el cual un vehículo puede ser retirado por una grúa y se deposite en el lote autorizado?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (66, '¿Qué tienen prohibido los pasajeros y ocupantes de vehículos?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (67, '¿Dónde queda prohibido rebasar?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (68, '¿Dónde están prohibidas las vueltas en U?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (69, '¿Cuál es velocidad máxima en zona escolar?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (70, '¿Qué significa una luz ámbar o amarilla destellando?', null);
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (71, '¿Qué significa esta señal?', '/images/1.webp');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (72, '¿Qué significa esta señal?', '/images/2.webp');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (73, '¿Qué significa esta señal?', '/images/3.webp');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (74, '¿Qué significa esta señal?', '/images/4.png');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (75, '¿Qué significa esta señal?', '/images/5.webp');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (76, '¿Qué significa esta señal?', '/images/6.png');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (77, '¿Qué significa esta señal?', '/images/7.webp');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (78, '¿Qué significa esta señal?', '/images/8.png');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (79, '¿Qué significa esta señal?', '/images/9.png');
INSERT INTO PREGUNTAS (ID_PREGUNTA, DESCRIPCION, IMAGEN_URL) VALUES (80, '¿Qué significa esta señal?', '/images/10.png');
